// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:evmrider/models/app_state.dart';
import 'package:evmrider/models/config.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppStateAdapter());
    registerAdapter(EthereumConfigAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppStateAdapter());
    registerAdapter(EthereumConfigAdapter());
  }
}
