name: Build Windows (x64)

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Enable Windows desktop target
        run: flutter config --enable-windows-desktop

      - name: Fetch packages
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release

      - name: Create ZIP
        shell: pwsh
        run: |
          # Flutter 3.19+ places output in x64/Release, older versions in runner/Release
          $primary   = "build/windows/x64/runner/Release"
          $fallback  = "build/windows/runner/Release"
          $outDir    = if (Test-Path $primary) { $primary } else { $fallback }

          if (-not (Test-Path $outDir)) {
            Write-Error "Release folder not found: $outDir"
            exit 1
          }

          Compress-Archive -Path "$outDir\*" -DestinationPath "build\evmrider-win-x64.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: evmrider-win-x64
          path: build/evmrider-win-x64.zip
